### ISSUE TITLE
Could not find dependency Package[libcouchbase2-libevent] 

### ISSUE THREAD

**Issue by Yamakasi** [justicel/puppet-couchbase#12]
Hi,

I'm trying this module with foreman so I need to comment out most parts in init.pp which runs the script but I get the following error for Ubuntu:

Could not find dependency Package[libcouchbase2-libevent] for Package[couchbase_python] at /etc/puppet/environments/common/couchbase/manifests/client/python.pp:23

What is going wrong here ?

Thanks.

**Comment by justicel** [comment]
Never heard back. Closing.
