### ISSUE TITLE
Downloads not available

### ISSUE THREAD

**Issue by ajcrowe** [justicel/puppet-couchbase#16]
It seems couchbase don't allow direct downloads anymore. Is there a way this module can be adapted to this new state of affairs?

**Comment by justicel** [comment]
I was afraid that day would come. I will look at their site and find out
what I can and speak to them if necessary.

**Comment by justicel** [comment]
I just checked. The downloads are still available, but only for the community version. If you select the community install that will allow you to install 3.0.1.

**Comment by ajcrowe** [comment]
Actually I think it works if you specify 3.0.2, perhaps they don't have a 'latest' available now?

**Comment by justicel** [comment]
The version I just released to the forge defaults to the community release. See if this works for you.

**Comment by justicel** [comment]
Oh. I just realized what your comment might be implying. Are you attempting to set the version manually to 'latest'? There isn't any logic in the scripts to translate that and there is no file called 'latest' on the couchbase servers. You have to hard set a version number, which is currently done in the defaults. I might add a variable verification for that.

**Comment by ajcrowe** [comment]
Ok i've worked out the confusion, your example has version set to 'latest' so I assumed this would work.

I got further confused because the download speed is very slow for me and so it was timing out, I'll close this, but perhaps an update to the docs?

**Comment by justicel** [comment]
Sure thing
